data = {
  Banner_image: [
    {
      bannername: '1651061999.jpg',
      created_on: '2021-01-22',
      id: '14',
      status: '1',
      type: '1',
      updated_on: '2022-04-27',
    },
    {
      bannername: '1651062077.jpg',
      created_on: '2017-12-30',
      id: '10',
      status: '1',
      type: '1',
      updated_on: '2022-04-27',
    },
    {
      bannername: '1584953745.jpg',
      created_on: '2017-12-14',
      id: '5',
      status: '1',
      type: '1',
      updated_on: '2020-03-23',
    },
    {
      bannername: '1584953157.jpg',
      created_on: '2017-12-14',
      id: '3',
      status: '1',
      type: '1',
      updated_on: '2020-03-23',
    },
  ],
  Premium_books: [
    {
      audiofile: '1748.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Dr. Satya Prakash Singh',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Hindutva Aandolan: Kya Kyu Aur Kaise ?',
      count: null,
      id: '1748',
      narrator: 'Divya Singh',
      percentage: null,
      photo: '1650488202.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1707.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: "Ayodhya Singh Upadhyay ‘Hari Oudh'",
      bookcategory: 'Poetry & Ghazal',
      bookcategoryid: '5',
      bookname: 'Karmaveer',
      count: null,
      id: '1707',
      narrator: 'Divya Singh',
      percentage: null,
      photo: '1646505861.jpg',
      rating: null,
      sampleplay_time: '55',
      viewcount: null,
    },
    {
      audiofile: '1706.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: "Ayodhya Singh Upadhyay ‘Hari Oudh'",
      bookcategory: 'Poetry & Ghazal',
      bookcategoryid: '5',
      bookname: 'Fool Aur Kaanta',
      count: null,
      id: '1706',
      narrator: 'Divya Singh',
      percentage: null,
      photo: '1646504883.jpg',
      rating: null,
      sampleplay_time: '40',
      viewcount: null,
    },
    {
      audiofile: '1606.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Jainandan',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Khairiyat Ki Khaak',
      count: null,
      id: '1606',
      narrator: 'Sanjay Srivastava',
      percentage: null,
      photo: '1610216828.jpg',
      rating: null,
      sampleplay_time: '300',
      viewcount: '46',
    },
    {
      audiofile: '1605.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Dr. Pushpita Awasthi',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Kancha',
      count: null,
      id: '1605',
      narrator: 'Divya Singh',
      percentage: null,
      photo: '1610216361.jpg',
      rating: null,
      sampleplay_time: '300',
      viewcount: '31',
    },
    {
      audiofile: '1518.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: "Madhav Giri 'Madhuban'",
      bookcategory: 'Poetry & Ghazal',
      bookcategoryid: '5',
      bookname: 'Hind Ke Sher',
      count: null,
      id: '1518',
      narrator: 'Maahi',
      percentage: null,
      photo: '1596713678.jpg',
      rating: null,
      sampleplay_time: '70',
      viewcount: '46',
    },
    {
      audiofile: '556.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'AVIS',
      bookcategory: 'City Voice',
      bookcategoryid: '9',
      bookname: 'Hawa Mahal-Jaipur',
      count: '1',
      id: '556',
      narrator: 'Sunil Shukla',
      percentage: '5.0',
      photo: '1647115684.jpg',
      rating: '5',
      sampleplay_time: '5',
      viewcount: '90',
    },
    {
      audiofile: '533.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Divik Ramesh',
      bookcategory: 'Poetry & Ghazal',
      bookcategoryid: '5',
      bookname: 'Ghar',
      count: null,
      id: '533',
      narrator: 'Sunil Shukla',
      percentage: null,
      photo: '1651482840.jpg',
      rating: null,
      sampleplay_time: '45',
      viewcount: '48',
    },
    {
      audiofile: '386.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Jaishree Roy',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Daud',
      count: null,
      id: '386',
      narrator: 'Shikha Singh',
      percentage: null,
      photo: '1650710730.jpg',
      rating: null,
      sampleplay_time: '130',
      viewcount: '99',
    },
    {
      audiofile: '303.mp3',
      book_type: 'BIV Original',
      book_type_color: 'red',
      bookauthor: 'Kamal',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Kim Len',
      count: null,
      id: '303',
      narrator: 'RJ Rekha Rani',
      percentage: null,
      photo: '1649960106.jpg',
      rating: null,
      sampleplay_time: '90',
      viewcount: '111',
    },
  ],
  advertise: [
    {
      created_at: '2022-04-21 12:39:57',
      id: '11',
      status: '1',
      title: '',
      url: 'upload/subscription/1650569997.jpg',
    },
  ],
  books_by_cate: [
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
    [[Object], [Object], [Object], [Object], [Object], [Object], [Object]],
  ],
  category: [
    {bookcategory: 'Books & Biography', catphoto: '1647116060.jpg', id: '2'},
    {bookcategory: 'Stories', catphoto: '1647115873.jpg', id: '4'},
    {bookcategory: 'Novels & Drama', catphoto: '1647115941.jpg', id: '3'},
    {bookcategory: 'City Voice', catphoto: '1647116036.jpg', id: '9'},
    {bookcategory: 'Adhyatma', catphoto: '1647116099.jpg', id: '13'},
    {bookcategory: 'Kids Corner', catphoto: '1646855483.jpg', id: '6'},
    {bookcategory: 'Poetry & Ghazal', catphoto: '1647115915.jpg', id: '5'},
    {bookcategory: 'Literature', catphoto: '1647115963.jpg', id: '1'},
    {bookcategory: 'Fauji Vani', catphoto: '1647115997.jpg', id: '11'},
    {bookcategory: 'Articles', catphoto: '1647116080.jpg', id: '7'},
  ],
  msg: 'New User',
  new_arrival: [
    {
      audiofile: '1766.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'P. G. Sahastrabuddhe',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Sanskaar Mala Bhag 2',
      count: null,
      id: '1766',
      narrator: 'Divya Singh',
      percentage: null,
      photo: '1650581066.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1764.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Govardhan Yadav',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Ye Raat Phir Na Aayegi',
      count: null,
      id: '1764',
      narrator: 'Rajinder Kaur',
      percentage: null,
      photo: '1650579278.jpg',
      rating: null,
      sampleplay_time: '100',
      viewcount: null,
    },
    {
      audiofile: '1763.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Madhu Kankariya',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Ve Das Minute',
      count: null,
      id: '1763',
      narrator: 'Shabnam',
      percentage: null,
      photo: '1650578970.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1762.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Sudha Arora',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Annpurna Mandal Ki Aakhiri Chitthi',
      count: null,
      id: '1762',
      narrator: 'Rajinder Kaur',
      percentage: null,
      photo: '1650578447.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1761.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'P. G. Sahastrabuddhe',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Sanskaar Mala Bhag 1',
      count: null,
      id: '1761',
      narrator: 'Anand Sharma',
      percentage: null,
      photo: '1650575835.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1760.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Akansha Pare ‘Kashiv’',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Panchvin Pandav',
      count: null,
      id: '1760',
      narrator: 'Shikha Singh',
      percentage: null,
      photo: '1650575162.jpg',
      rating: null,
      sampleplay_time: '120',
      viewcount: null,
    },
    {
      audiofile: '1759.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Basant Tripathi',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Pita',
      count: null,
      id: '1759',
      narrator: 'Rajinder Kaur',
      percentage: null,
      photo: '1650574930.jpg',
      rating: null,
      sampleplay_time: '120',
      viewcount: null,
    },
    {
      audiofile: '1758.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Rajni Gupt',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Parshaw Sangeet',
      count: null,
      id: '1758',
      narrator: 'Shikha Singh',
      percentage: null,
      photo: '1650574562.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
    {
      audiofile: '1757.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Sudha Arora',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Kaanse Ka Glass',
      count: null,
      id: '1757',
      narrator: 'Rajinder Kaur',
      percentage: null,
      photo: '1650574060.jpg',
      rating: null,
      sampleplay_time: '119',
      viewcount: null,
    },
    {
      audiofile: '1756.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Satyapal Patait',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Guru Tegh Bahadur',
      count: null,
      id: '1756',
      narrator: 'Anand Sharma',
      percentage: null,
      photo: '1650573398.jpg',
      rating: null,
      sampleplay_time: '150',
      viewcount: null,
    },
  ],
  populars_books: [
    {
      audiofile: '893.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Deendayal Upadhyaya',
      bookcategory: 'Literature',
      bookcategoryid: '1',
      bookname: 'Rajya Ki Nirankushta',
      count: '1',
      id: '893',
      narrator: 'Maahi',
      percentage: '5.0',
      photo: '1570883648.jpg',
      rating: '5',
      sampleplay_time: '45',
      viewcount: '34',
    },
    {
      audiofile: '1512.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: '‘Kaipu’ Laxmi Narsingh Shastri, Translator- C. L. Sharma',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Shri Ram',
      count: '1',
      id: '1512',
      narrator: 'Sandeep Sharma',
      percentage: '5.0',
      photo: '1596484287.jpg',
      rating: '5',
      sampleplay_time: '2800',
      viewcount: '71',
    },
    {
      audiofile: '1107.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Saadat Hasan Manto ',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Boo',
      count: '1',
      id: '1107',
      narrator: 'Sunil Shukla',
      percentage: '5.0',
      photo: '1576689999.jpg',
      rating: '5',
      sampleplay_time: '150',
      viewcount: '29',
    },
    {
      audiofile: '380.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Rajni Gupt',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Akhiri Sawaal',
      count: '1',
      id: '380',
      narrator: 'Rajinder Kaur',
      percentage: '5.0',
      photo: '1526306970.jpg',
      rating: '5',
      sampleplay_time: '60',
      viewcount: '132',
    },
    {
      audiofile: '1598.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Madhu Kankariya',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Polythene Men Prithvi',
      count: '1',
      id: '1598',
      narrator: 'Lokesh Gupta',
      percentage: '5.0',
      photo: '1608925514.jpg',
      rating: '5',
      sampleplay_time: '250',
      viewcount: '40',
    },
    {
      audiofile: '708.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: "Kiran Rajpurohit 'Nitila'",
      bookcategory: 'Poetry & Ghazal',
      bookcategoryid: '5',
      bookname: 'Gathari Khwahishon Ki',
      count: '1',
      id: '708',
      narrator: 'Maahi',
      percentage: '5.0',
      photo: '1556959470.jpg',
      rating: '5',
      sampleplay_time: '40',
      viewcount: '92',
    },
    {
      audiofile: '1071.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: "Omprakash Kshatriya 'Prakash'",
      bookcategory: 'Kids Corner',
      bookcategoryid: '6',
      bookname: 'Badal Mar Gaya',
      count: '2',
      id: '1071',
      narrator: 'Pragya Jha',
      percentage: '5.0',
      photo: '1575805660.jpg',
      rating: '10',
      sampleplay_time: '70',
      viewcount: '62',
    },
    {
      audiofile: '1485.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Rasik Puttige, Translator- Omprakash Shiv',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Tulsidas',
      count: '1',
      id: '1485',
      narrator: 'Anand Sharma',
      percentage: '5.0',
      photo: '1595861283.jpg',
      rating: '5',
      sampleplay_time: '300',
      viewcount: '52',
    },
    {
      audiofile: '496.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Tapaswini Dasi, Translator- Manju',
      bookcategory: 'Adhyatma',
      bookcategoryid: '13',
      bookname: 'Radha Rani Ka Prakatya',
      count: '1',
      id: '496',
      narrator: 'Maahi',
      percentage: '5.0',
      photo: '1533932710.jpg',
      rating: '5',
      sampleplay_time: '55',
      viewcount: '158',
    },
    {
      audiofile: '1121.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Ashok Mishra',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Vilom',
      count: '1',
      id: '1121',
      narrator: 'Hemant Mohan',
      percentage: '5.0',
      photo: '1576866355.jpg',
      rating: '5',
      sampleplay_time: '65',
      viewcount: '38',
    },
  ],
  response: '800',
  top_rated: [
    {
      audiofile: '494.mp3',
      book_type: '',
      book_type_color: null,
      bookauthor: 'Tapaswini Dasi, Translator- Manju',
      bookcategory: 'Adhyatma',
      bookcategoryid: '13',
      bookname: 'Swachha Bharat',
      count: '60',
      id: '494',
      narrator: 'Maahi',
      percentage: '3.5',
      photo: '1533930995.jpg',
      rating: '212',
      sampleplay_time: '50',
      viewcount: '203',
    },
    {
      audiofile: '493.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Manju',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Shunya',
      count: '22',
      id: '493',
      narrator: 'Dr. Madhulika Shrivastava',
      percentage: '3.8',
      photo: '1650701900.jpg',
      rating: '83',
      sampleplay_time: '5',
      viewcount: '297',
    },
    {
      audiofile: '1610.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Anupama Tiwadi',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Mahatwakankshayen Adhuri-Puri',
      count: '16',
      id: '1610',
      narrator: 'Lokesh Gupta',
      percentage: '3.3',
      photo: '1617823796.jpg',
      rating: '52',
      sampleplay_time: '200',
      viewcount: '18',
    },
    {
      audiofile: '1457.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Shri Murthy, Translator- Ku. Sadhna Sharma',
      bookcategory: 'Books & Biography',
      bookcategoryid: '2',
      bookname: 'Shri Krishna',
      count: '6',
      id: '1457',
      narrator: 'Anand Sharma',
      percentage: '5.0',
      photo: '1593286569.jpg',
      rating: '30',
      sampleplay_time: '200',
      viewcount: '181',
    },
    {
      audiofile: '1238.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'AVIS',
      bookcategory: 'Articles',
      bookcategoryid: '7',
      bookname: 'Corona Virus?',
      count: '6',
      id: '1238',
      narrator: 'Maahi',
      percentage: '5.0',
      photo: '1580919334.jpg',
      rating: '30',
      sampleplay_time: '600',
      viewcount: '172',
    },
    {
      audiofile: '224.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Rajni Gosain',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Ajnabi',
      count: '6',
      id: '224',
      narrator: 'RJ Rekha Rani',
      percentage: '4.3',
      photo: '1650441644.jpg',
      rating: '26',
      sampleplay_time: '60',
      viewcount: '175',
    },
    {
      audiofile: '77.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Avis',
      bookcategory: 'City Voice',
      bookcategoryid: '9',
      bookname: 'City Voice',
      count: '4',
      id: '77',
      narrator: 'Sunil Shukla',
      percentage: '5.0',
      photo: '1517771237.jpg',
      rating: '20',
      sampleplay_time: '48',
      viewcount: '122',
    },
    {
      audiofile: '1037.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Anupama Tiwadi',
      bookcategory: 'Stories',
      bookcategoryid: '4',
      bookname: 'Tare',
      count: '4',
      id: '1037',
      narrator: 'Lokesh Gupta',
      percentage: '5.0',
      photo: '1575035677.jpg',
      rating: '20',
      sampleplay_time: '100',
      viewcount: '149',
    },
    {
      audiofile: '432.mp3',
      book_type: null,
      book_type_color: null,
      bookauthor: 'Vivek Ranjan Shrivastava',
      bookcategory: 'Literature',
      bookcategoryid: '1',
      bookname: 'Computer Peedit',
      count: '4',
      id: '432',
      narrator: 'Sanjay Srivastava',
      percentage: '4.8',
      photo: '1527406955.jpg',
      rating: '19',
      sampleplay_time: '50',
      viewcount: '195',
    },
    {
      audiofile: '374.mp3',
      book_type: '',
      book_type_color: '',
      bookauthor: 'Yashoda Devi',
      bookcategory: 'Novels & Drama',
      bookcategoryid: '3',
      bookname: 'Sachha Pati Prem',
      count: '4',
      id: '374',
      narrator: 'Maahi',
      percentage: '4.5',
      photo: '1650525586.jpg',
      rating: '18',
      sampleplay_time: '50',
      viewcount: '151',
    },
  ],
};
